### ISSUE TITLE
Which version of raspicam?

### ISSUE THREAD

**Issue by spinoza1791** [shadowkane/darknet-nnpack-opencv4.0-raspicam#1]
Do you have instructions or link to installing the correct raspicam to the Pi and getting the libraries referenced in 

Package raspicam was not found in the pkg-config search path.
Perhaps you should add the directory containing `raspicam.pc'
to the PKG_CONFIG_PATH environment variable
No package 'raspicam' found

fatal error: raspicam/raspicam_cv.h: No such file or directory
 #include "raspicam/raspicam_cv.h

**Comment by shadowkane** [comment]
i have this link for the raspicam library : https://www.uco.es/investiga/grupos/ava/node/40
you can download the latest version and test it with a simple c++ program.
and before installing this library configure the makefile. the OPENCV and RASPICAM variable are not to install those libraries. your configuration will determine if the darknet will use opencv and raspicam or not.
they are no need to include the installation of opencv and raspicam and other libraries like them to this one. opencv and raspicam are a easy to be installed and many tutorial are exist in the web.
by the way you can check my video in youtube "https://www.youtube.com/watch?v=f-83nAdmFAA" to how install opencv and raspicam (it was for QT creator) in raspberry pi but will work the same.  sorry for the delay.
